/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.Ventas;

import Clases.Colores;
import java.awt.Dimension;

/**
 *
 * @author julio
 */
public class Ventas extends javax.swing.JPanel {

    Venta_Directa vd = new Venta_Directa();
    Sistema_Apartado sa = new Sistema_Apartado();
    Abono_Pagos ap = new Abono_Pagos();
    boolean clickedv = true;
    boolean clickeda = false;
    boolean clickedp = false;

    /**
     * Creates new form Venta_Directa
     */
    public Ventas() {
        initComponents();
        diseñar_form();
    }

    private void diseñar_form() {
        pnlContenedor.add(vd);
        int height2 = this.getSize().height;
        int width2 = this.getSize().width;
        this.setMaximumSize(new Dimension(width2, height2));
        this.setBackground(Colores.texto_botones_clicked);
        this.pnlMenu.setBackground(Colores.fondo_primario);
        this.btnAP.setBackground(Colores.fondo_primario);
        this.btnAP.setOpaque(true);
        this.btnSA.setBackground(Colores.fondo_primario);
        this.btnSA.setOpaque(true);
        this.btnVD.setBackground(Colores.fondo_primario_oscuro);
        this.btnVD.setOpaque(true);
        this.btnVD.setForeground(Colores.texto_botones_clicked);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnVD = new javax.swing.JLabel();
        btnSA = new javax.swing.JLabel();
        btnAP = new javax.swing.JLabel();

        setBackground(new java.awt.Color(227, 159, 159));

        pnlContenedor.setLayout(new java.awt.BorderLayout());

        btnVD.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        btnVD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVD.setText("Venta directa");
        btnVD.setAlignmentY(0.0F);
        btnVD.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVDMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVDMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVDMouseEntered(evt);
            }
        });

        btnSA.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        btnSA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSA.setText("Sistema de apartado");
        btnSA.setAlignmentY(0.0F);
        btnSA.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSAMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSAMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSAMouseEntered(evt);
            }
        });

        btnAP.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        btnAP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAP.setText("Abono de pagos");
        btnAP.setAlignmentY(0.0F);
        btnAP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAPMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAPMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAPMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnVD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnSA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnAP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pnlContenedor.add(pnlMenu, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVDMouseClicked
        // TODO add your handling code here:
        deshabilitar_paneles(true, false, false);
        pnlContenedor.add(vd);
        pnlContenedor.validate();
        deshabilitar_botones(true, false, false);
        colorear_botones();
    }//GEN-LAST:event_btnVDMouseClicked

    private void btnVDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVDMouseExited
        // TODO add your handling code here:
        if (!clickedv) {
            btnVD.setBackground(Colores.fondo_primario);
            btnVD.setOpaque(true);
        }
    }//GEN-LAST:event_btnVDMouseExited

    private void btnVDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVDMouseEntered
        // TODO add your handling code here:
        if (!clickedv) {
            btnVD.setBackground(Colores.fondo_primario_oscuro);
            btnVD.setOpaque(true);
        }
    }//GEN-LAST:event_btnVDMouseEntered

    private void btnSAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSAMouseClicked
        // TODO add your handling code here:
        deshabilitar_paneles(false, true, false);
        pnlContenedor.add(sa);
        pnlContenedor.validate();
        deshabilitar_botones(false, true, false);
        colorear_botones();
    }//GEN-LAST:event_btnSAMouseClicked

    private void btnSAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSAMouseExited
        // TODO add your handling code here:
        if (!clickeda) {
            btnSA.setBackground(Colores.fondo_primario);
            btnSA.setOpaque(true);
        }
    }//GEN-LAST:event_btnSAMouseExited

    private void btnSAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSAMouseEntered
        // TODO add your handling code here:
        if (!clickeda) {
            btnSA.setBackground(Colores.fondo_primario_oscuro);
            btnSA.setOpaque(true);
        }
    }//GEN-LAST:event_btnSAMouseEntered

    private void btnAPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAPMouseEntered
        // TODO add your handling code here:
        if (!clickedp) {
            btnAP.setBackground(Colores.fondo_primario_oscuro);
            btnAP.setOpaque(true);
        }
    }//GEN-LAST:event_btnAPMouseEntered

    private void btnAPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAPMouseExited
        // TODO add your handling code here:
        if (!clickedp) {
            btnAP.setBackground(Colores.fondo_primario);
            btnAP.setOpaque(true);
        }
    }//GEN-LAST:event_btnAPMouseExited

    private void btnAPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAPMouseClicked
        // TODO add your handling code here:
        deshabilitar_paneles(false, false, true);
        pnlContenedor.add(ap);
        pnlContenedor.validate();
        deshabilitar_botones(false, false, true);
        colorear_botones();
    }//GEN-LAST:event_btnAPMouseClicked

   private void deshabilitar_botones(boolean v, boolean a, boolean p) {
        this.clickedv = v;
        this.clickeda = a;
        this.clickedp = p;
    }

    private void deshabilitar_paneles(boolean vd, boolean sa, boolean ap) {
        this.vd.setVisible(vd);
        this.sa.setVisible(sa);
        this.ap.setVisible(ap);
    }

    private void colorear_botones() {
        this.btnVD.setBackground(this.clickedv ? Colores.fondo_primario_oscuro : Colores.fondo_primario);
        this.btnSA.setBackground(this.clickeda ? Colores.fondo_primario_oscuro : Colores.fondo_primario);
        this.btnAP.setBackground(this.clickedp ? Colores.fondo_primario_oscuro : Colores.fondo_primario);

        this.btnVD.setForeground(this.clickedv ? Colores.texto_botones_clicked : Colores.texto_botones);
        this.btnSA.setForeground(this.clickeda ? Colores.texto_botones_clicked : Colores.texto_botones);
        this.btnAP.setForeground(this.clickedp ? Colores.texto_botones_clicked : Colores.texto_botones);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAP;
    private javax.swing.JLabel btnSA;
    private javax.swing.JLabel btnVD;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
