/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.Reportes;

import Forms.Proveedores.*;
import Clases.Colores;

/**
 *
 * @author jandr
 */
public class Reportes extends javax.swing.JPanel {

    Reporte_Dia rd;
    Reporte_Semana rs = new Reporte_Semana();
    Otros_Reportes or = new Otros_Reportes();
    boolean clickedd = true;
    boolean clickeds = false;
    boolean clickedo = false;

    /**
     * Creates new form Proveedores
     */
    public Reportes() {
        initComponents();
        rd = new Reporte_Dia();
        diseñar_form();
    }

    private void diseñar_form() {
        this.setBackground(Colores.texto_botones_clicked);
        this.pnlMenu.setBackground(Colores.fondo_primario);
        this.btnOtros.setBackground(Colores.fondo_primario);
        this.btnOtros.setOpaque(true);
        this.btnSemanal.setBackground(Colores.fondo_primario);
        this.btnSemanal.setOpaque(true);
        this.btnDiario.setBackground(Colores.fondo_primario_oscuro);
        this.btnDiario.setOpaque(true);
        this.btnDiario.setForeground(Colores.texto_botones_clicked);
        pnlContenedor.add(rd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnDiario = new javax.swing.JLabel();
        btnSemanal = new javax.swing.JLabel();
        btnOtros = new javax.swing.JLabel();

        pnlContenedor.setLayout(new java.awt.BorderLayout());

        btnDiario.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        btnDiario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDiario.setText("Ventas por día");
        btnDiario.setAlignmentY(0.0F);
        btnDiario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDiario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDiarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDiarioMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDiarioMouseEntered(evt);
            }
        });

        btnSemanal.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        btnSemanal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSemanal.setText("Ventas entre 2 fechas");
        btnSemanal.setAlignmentY(0.0F);
        btnSemanal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSemanal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSemanalMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSemanalMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSemanalMouseEntered(evt);
            }
        });

        btnOtros.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        btnOtros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnOtros.setText("Inventario");
        btnOtros.setAlignmentY(0.0F);
        btnOtros.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOtros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOtrosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOtrosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOtrosMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnDiario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnSemanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnOtros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSemanal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pnlContenedor.add(pnlMenu, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDiarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiarioMouseClicked
        // TODO add your handling code here:
        deshabilitar_paneles(true, false, false);
        pnlContenedor.add(rd);
        pnlContenedor.validate();
        deshabilitar_botones(true, false, false);
        colorear_botones();
    }//GEN-LAST:event_btnDiarioMouseClicked

    private void btnDiarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiarioMouseExited
        // TODO add your handling code here:
        if (!clickedd) {
            btnDiario.setBackground(Colores.fondo_primario);
            btnDiario.setOpaque(true);
        }
    }//GEN-LAST:event_btnDiarioMouseExited

    private void btnDiarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiarioMouseEntered
        // TODO add your handling code here:
        if (!clickedd) {
            btnDiario.setBackground(Colores.fondo_primario_oscuro);
            btnDiario.setOpaque(true);
        }
    }//GEN-LAST:event_btnDiarioMouseEntered

    private void btnSemanalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSemanalMouseClicked
        // TODO add your handling code here:
        deshabilitar_paneles(false, true, false);
        pnlContenedor.add(rs);
        pnlContenedor.validate();
        deshabilitar_botones(false, true, false);
        colorear_botones();
    }//GEN-LAST:event_btnSemanalMouseClicked

    private void btnSemanalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSemanalMouseExited
        // TODO add your handling code here:
        if (!clickeds) {
            btnSemanal.setBackground(Colores.fondo_primario);
            btnSemanal.setOpaque(true);
        }
    }//GEN-LAST:event_btnSemanalMouseExited

    private void btnSemanalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSemanalMouseEntered
        // TODO add your handling code here:
        if (!clickeds) {
            btnSemanal.setBackground(Colores.fondo_primario_oscuro);
            btnSemanal.setOpaque(true);
        }
    }//GEN-LAST:event_btnSemanalMouseEntered

    private void btnOtrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOtrosMouseClicked
        // TODO add your handling code here:
        deshabilitar_paneles(false, false, true);
        pnlContenedor.add(or);
        pnlContenedor.validate();
        deshabilitar_botones(false, false, true);
        colorear_botones();
    }//GEN-LAST:event_btnOtrosMouseClicked

    private void btnOtrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOtrosMouseExited
        // TODO add your handling code here:
        if (!clickedo) {
            btnOtros.setBackground(Colores.fondo_primario);
            btnOtros.setOpaque(true);
        }
    }//GEN-LAST:event_btnOtrosMouseExited

    private void btnOtrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOtrosMouseEntered
        // TODO add your handling code here:
        if (!clickedo) {
            btnOtros.setBackground(Colores.fondo_primario_oscuro);
            btnOtros.setOpaque(true);
        }
    }//GEN-LAST:event_btnOtrosMouseEntered

    private void deshabilitar_botones(boolean r, boolean m, boolean e) {
        this.clickedd = r;
        this.clickeds = m;
        this.clickedo = e;
    }

    private void deshabilitar_paneles(boolean rc, boolean mc, boolean ec) {
        this.rd.setVisible(rc);
        this.rs.setVisible(mc);
        this.or.setVisible(ec);
    }

    private void colorear_botones() {
        this.btnDiario.setBackground(this.clickedd ? Colores.fondo_primario_oscuro : Colores.fondo_primario);
        this.btnSemanal.setBackground(this.clickeds ? Colores.fondo_primario_oscuro : Colores.fondo_primario);
        this.btnOtros.setBackground(this.clickedo ? Colores.fondo_primario_oscuro : Colores.fondo_primario);

        this.btnDiario.setForeground(this.clickedd ? Colores.texto_botones_clicked : Colores.texto_botones);
        this.btnSemanal.setForeground(this.clickeds ? Colores.texto_botones_clicked : Colores.texto_botones);
        this.btnOtros.setForeground(this.clickedo ? Colores.texto_botones_clicked : Colores.texto_botones);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDiario;
    private javax.swing.JLabel btnOtros;
    private javax.swing.JLabel btnSemanal;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
