/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.Vendedores;

import Clases.BD;
import Clases.CRUD;
import Clases.Colores;
import Clases.Strings;
import Clases.Vista;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author julio
 */
public class Registrar_Vendedor2 extends javax.swing.JPanel {

    private String nombre = "";
    private String usuario = "";
    private String contraseña = "";
    private String confirmacion = "";

    /**
     * Creates new form Agregar_Vendedor
     */
    public Registrar_Vendedor2() {
        initComponents();
        diseñar_form();
    }

    private void diseñar_form() {
        this.setBackground(Colores.texto_botones_clicked);
        this.pnlContenedor.setBackground(Colores.fondo_primario_claro);
        this.lblTitulo.setText(Strings.agregar_vendedor);
        this.lblNombre.setText(Strings.nombre_vendedor);
        this.lblUsuario.setText(Strings.usuario_vendedor);
        this.lblContraseña.setText(Strings.contraseña);
        this.lblConfirmacion.setText(Strings.contraseña_confirmacion);
        this.btnAgregar.setText(Strings.agregar_vendedor);
        this.btnAgregar.setBackground(Colores.fondo_botones);
        this.btnAgregar.setForeground(Colores.texto_botones);
        this.lblGif.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        pnlRegistrar = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        txtConfirmacion = new javax.swing.JPasswordField();
        lblContraseña = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        lblConfirmacion = new javax.swing.JLabel();
        lblGif = new javax.swing.JLabel();

        setBackground(new java.awt.Color(162, 60, 60));
        setPreferredSize(new java.awt.Dimension(657, 458));

        pnlContenedor.setPreferredSize(new java.awt.Dimension(651, 446));
        pnlContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblTitulo.setText("jLabel1");

        lblNombre.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblNombre.setText("jLabel1");

        txtNombre.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        txtNombre.setPreferredSize(new java.awt.Dimension(200, 27));

        txtUsuario.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N

        txtContraseña.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });

        txtConfirmacion.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N

        lblContraseña.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblContraseña.setText("jLabel1");

        lblUsuario.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblUsuario.setText("jLabel1");

        btnAgregar.setText("jButton1");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblConfirmacion.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblConfirmacion.setText("jLabel1");

        lblGif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loader.gif"))); // NOI18N

        javax.swing.GroupLayout pnlRegistrarLayout = new javax.swing.GroupLayout(pnlRegistrar);
        pnlRegistrar.setLayout(pnlRegistrarLayout);
        pnlRegistrarLayout.setHorizontalGroup(
            pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregar)
                    .addGroup(pnlRegistrarLayout.createSequentialGroup()
                        .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addGap(50, 50, 50)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                                .addComponent(lblUsuario)
                                .addGap(50, 50, 50)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContraseña, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblConfirmacion, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(50, 50, 50)
                        .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtContraseña)
                            .addComponent(txtConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGif, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRegistrarLayout.setVerticalGroup(
            pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContraseña)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirmacion)
                    .addComponent(txtConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGif, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pnlContenedor.add(pnlRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        new agregar_vendedor().show();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    public void clear_text(boolean usuario, boolean pass, boolean confirmacion, boolean fUsuario, boolean fPass, boolean fConfi) {
        if (usuario) {
            this.txtUsuario.setText("");
        }
        if (pass) {
            this.txtContraseña.setText("");
        }
        if (confirmacion) {
            this.txtConfirmacion.setText("");
        }
        if (fUsuario) {
            this.txtUsuario.requestFocus();
        }
        if (fPass) {
            this.txtContraseña.requestFocus();
        }
        if (fConfi) {
            this.txtConfirmacion.requestFocus();
        }
    }

    public void mostrar_loading(boolean show) {
        this.btnAgregar.setVisible(!show);
        this.lblGif.setVisible(show);
    }

    public class agregar_vendedor implements Runnable {

        public void show() {
            new Thread(this).start();
        }

        @Override
        public void run() {
            int reply = JOptionPane.showConfirmDialog(null, Strings.confirmar_insertar_vendedor, Strings.ventana_informacion_titulo, JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
            mostrar_loading(true);
                if (campos_llenos()) {
                    if (contraseñas_iguales()) {
                        try {
                            if (CRUD.conexion_internet()) {
                                if (!CRUD.existe_usuario(usuario)) {
                                    if (CRUD.insertar_vendedor(nombre, contraseña, usuario) != 0) {
                                        mostrar_loading(false);
                                        clear_text(true, true, true, false, false, false);
                                        Vista.mensaje_informacion(Strings.vendedor_agregado, Strings.ventana_informacion_titulo);
                                    } else {
                                        mostrar_loading(false);
                                        Vista.mensaje_error(Strings.error_desconocido, Strings.titulo_error_vendedor);
                                    }
                                } else {
                                    mostrar_loading(false);
                                    clear_text(true, false, false, true, false, false);
                                    Vista.mensaje_error(Strings.usuario_existente, Strings.titulo_error_vendedor);
                                }
                            } else {
                                mostrar_loading(false);
                                Vista.mensaje_error(Strings.sin_internet, Strings.titulo_error_vendedor);
                            }
                        } catch (InterruptedException | IOException | SQLException | ClassNotFoundException ex) {
                            mostrar_loading(false);
                            Logger.getLogger(Registrar_Vendedor2.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        mostrar_loading(false);
                        clear_text(false, true, true, false, true, false);
                        Vista.mensaje_error(Strings.contraseñas_distintas, Strings.titulo_error_vendedor);
                    }
                } else {
                    mostrar_loading(false);
                    Vista.mensaje_error(Strings.campos_vacios, Strings.titulo_error_vendedor);
                }
            }
        }
    }

    private boolean contraseñas_iguales() {
        if (contraseña.equals(confirmacion)) {
            return true;
        } else {
            return false;
        }
    }

    private boolean campos_llenos() {
        nombre = this.txtNombre.getText();
        usuario = this.txtUsuario.getText();
        contraseña = new String(this.txtContraseña.getPassword());
        confirmacion = new String(this.txtConfirmacion.getPassword());
        if (nombre.equals("") || nombre == null) {
            return false;
        } else if (usuario.equals("") || usuario == null) {
            return false;
        } else if (contraseña.equals("") || contraseña == null) {
            return false;
        } else if (confirmacion.equals("") || confirmacion == null) {
            return false;
        } else {
            return true;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel lblConfirmacion;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblGif;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlRegistrar;
    private javax.swing.JPasswordField txtConfirmacion;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
