/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.Vendedores;

import Clases.Colores;

/**
 *
 * @author julio
 */
public class Vendedores extends javax.swing.JPanel {

    Registrar_Vendedor rv = new Registrar_Vendedor();
    Modificar_Vendedor mv = new Modificar_Vendedor();
    Eliminar_Vendedor ev = new Eliminar_Vendedor();
    boolean clickedr = true;
    boolean clickedm = false;
    boolean clickede = false;
    
    /**
     * Creates new form Vendedores
     */
    public Vendedores() {
        initComponents();
        diseñar_form();
    }

    private void diseñar_form() {
        this.setBackground(Colores.texto_botones_clicked);
        this.pnlMenu.setBackground(Colores.fondo_primario);
        this.btnEliminar.setBackground(Colores.fondo_primario);
        this.btnEliminar.setOpaque(true);
        this.btnModificar.setBackground(Colores.fondo_primario);
        this.btnModificar.setOpaque(true);
        this.btnRegistrar.setBackground(Colores.fondo_primario_oscuro);
        this.btnRegistrar.setOpaque(true);
        this.btnRegistrar.setForeground(Colores.texto_botones_clicked);
        pnlContenedor.add(rv);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JLabel();
        btnModificar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));

        pnlContenedor.setLayout(new java.awt.BorderLayout());

        pnlMenu.setPreferredSize(new java.awt.Dimension(616, 80));

        btnRegistrar.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        btnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setText("Registrar");
        btnRegistrar.setAlignmentY(0.0F);
        btnRegistrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseEntered(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        btnModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnModificar.setText("Modificar");
        btnModificar.setAlignmentY(0.0F);
        btnModificar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarMouseEntered(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        btnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminar.setText("Eliminar");
        btnEliminar.setAlignmentY(0.0F);
        btnEliminar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pnlContenedor.add(pnlMenu, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        deshabilitar_paneles(true, false, false);
        pnlContenedor.add(rv);
        pnlContenedor.validate();
        deshabilitar_botones(true, false, false);
        colorear_botones();
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseExited
        // TODO add your handling code here:
        if (!clickedr) {
            btnRegistrar.setBackground(Colores.fondo_primario);
            btnRegistrar.setOpaque(true);
        }
    }//GEN-LAST:event_btnRegistrarMouseExited

    private void btnRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseEntered
        // TODO add your handling code here:
        if (!clickedr) {
            btnRegistrar.setBackground(Colores.fondo_primario_oscuro);
            btnRegistrar.setOpaque(true);
        }
    }//GEN-LAST:event_btnRegistrarMouseEntered

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        // TODO add your handling code here:
        deshabilitar_paneles(false, true, false);
        pnlContenedor.add(mv);
        pnlContenedor.validate();
        deshabilitar_botones(false, true, false);
        colorear_botones();
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseExited
        // TODO add your handling code here:
        if (!clickedm) {
            btnModificar.setBackground(Colores.fondo_primario);
            btnModificar.setOpaque(true);
        }
    }//GEN-LAST:event_btnModificarMouseExited

    private void btnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseEntered
        // TODO add your handling code here:
        if (!clickedm) {
            btnModificar.setBackground(Colores.fondo_primario_oscuro);
            btnModificar.setOpaque(true);
        }
    }//GEN-LAST:event_btnModificarMouseEntered

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        deshabilitar_paneles(false, false, true);
        pnlContenedor.add(ev);
        pnlContenedor.validate();
        deshabilitar_botones(false, false, true);
        colorear_botones();
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        // TODO add your handling code here:
        if (!clickede) {
            btnEliminar.setBackground(Colores.fondo_primario);
            btnEliminar.setOpaque(true);
        }
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        // TODO add your handling code here:
        if (!clickede) {
            btnEliminar.setBackground(Colores.fondo_primario_oscuro);
            btnEliminar.setOpaque(true);
        }
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void deshabilitar_botones(boolean r, boolean m, boolean e) {
        this.clickedr = r;
        this.clickedm = m;
        this.clickede = e;
    }

    private void deshabilitar_paneles(boolean rc, boolean mc, boolean ec) {
        this.rv.setVisible(rc);
        this.mv.setVisible(mc);
        this.ev.setVisible(ec);
    }

    private void colorear_botones() {
        this.btnRegistrar.setBackground(this.clickedr ? Colores.fondo_primario_oscuro : Colores.fondo_primario);
        this.btnModificar.setBackground(this.clickedm ? Colores.fondo_primario_oscuro : Colores.fondo_primario);
        this.btnEliminar.setBackground(this.clickede ? Colores.fondo_primario_oscuro : Colores.fondo_primario);

        this.btnRegistrar.setForeground(this.clickedr ? Colores.texto_botones_clicked : Colores.texto_botones);
        this.btnModificar.setForeground(this.clickedm ? Colores.texto_botones_clicked : Colores.texto_botones);
        this.btnEliminar.setForeground(this.clickede ? Colores.texto_botones_clicked : Colores.texto_botones);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnModificar;
    private javax.swing.JLabel btnRegistrar;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
